### ISSUE TITLE
Exploring Colaboratory For Notebook Sharing

### ISSUE THREAD

**Issue by MarkDWilliams** [ncats/translator-workflows#59]
I've been exploring ways for us to share editable and executable notebooks with people without the need for them to spin up their own Jupyter environment and [Colaboratory](https://colab.research.google.com/notebooks/basic_features_overview.ipynb) from Google seems to fit the bill.  I've already uploaded a few notebooks to test, and ones which are self-contained (requiring only publicly available packages) seem to work fine, but there are some issues with notebooks that import code found elsewhere in the GitHub repo.  I wanted to get people's thoughts on using Colaboratory and any ideas for resolving issues with intra-repo dependencies.  I've included links to a few notebooks below.
These seem to work fine:
[https://colab.research.google.com/github/ncats/translator-workflows/blob/master/greengamma/workflow1/module3/module/module3_ROBOKOP.ipynb](https://colab.research.google.com/github/ncats/translator-workflows/blob/master/greengamma/workflow1/module3/module/module3_ROBOKOP.ipynb)
[https://colab.research.google.com/github/ncats/translator-workflows/blob/master/xray/WF1_2.1.ipynb#scrollTo=sN-Jj1USgHh7](https://colab.research.google.com/github/ncats/translator-workflows/blob/master/xray/WF1_2.1.ipynb#scrollTo=sN-Jj1USgHh7)
This one has issues with dependencies:
[https://colab.research.google.com/github/NCATS-Tangerine/mvp-module-library/blob/master/WF2_FA_human.ipynb](https://colab.research.google.com/github/NCATS-Tangerine/mvp-module-library/blob/master/WF2_FA_human.ipynb)

**Comment by cmungall** [comment]
There is also https://mybinder.org/

It won't necessarily run on the existing notebooks in this repo as it requires either a requirements.txt or a Dockerfile. But in theory the dependencies are more under our control here

**Comment by MarkDWilliams** [comment]
Binder instance can be found here
https://mybinder.org/v2/gh/ncats/translator-workflows/master

**Comment by cmungall** [comment]
ccing @diatomsRcool as I think she was working on this too

**Comment by diatomsRcool** [comment]
Yes. That's it.
