### ISSUE TITLE
Workflow 3B, Module 1: Experiment

### ISSUE THREAD

**Issue by karafecho** [ncats/translator-workflows#62]
Major histocompatibility complex (MHC) refers to a large group of genes that code for proteins that play an essential role in which of the following?
a. Antigen presentation to T lymphocytes
b. Phagocytosis by neutrophils
c. Antigen presentation to B lymphocytes
d. Phagocytosis by macrophages

  | n2 - id | n2 - name | score
-- | -- | -- | --
GO:0006955 | immune response | 2.722759
GO:0060333 | interferon-gamma-mediated signaling pathway | 2.334938
GO:0042605 | peptide antigen binding | 2.030128
GO:0019886 | antigen processing and presentation of exogenous peptide antigen via MHC class II | 1.945948
GO:0002504 | antigen processing and presentation of peptide or polysaccharide antigen via MHC class II | 1.686622
GO:0050852 | T cell receptor signaling pathway | 1.470677
GO:0032395 | MHC class II receptor activity | 1.167969
GO:0002376 | immune system process | 1.101306
GO:0005102 | signaling receptor binding | 1.014048
GO:0050776 | regulation of immune response | 0.992633
GO:0002474 | antigen processing and presentation of peptide antigen via MHC class I | 0.908642
GO:0060337 | type I interferon signaling pathway | 0.908642
GO:0001916 | positive regulation of T cell mediated cytotoxicity | 0.908642
GO:0002480 | antigen processing and presentation of exogenous peptide antigen via MHC class I, TAP-independent | 0.908642
GO:0002479 | antigen processing and presentation of exogenous peptide antigen via MHC class I, TAP-dependent | 0.908642
GO:0002476 | antigen processing and presentation of endogenous peptide antigen via MHC class Ib | 0.908642
GO:0023026 | MHC class II protein complex binding | 0.778979
GO:0043312 | neutrophil degranulation | 0.519653
GO:0030881 | beta-2-microglobulin binding | 0.389990
GO:0002503 | peptide antigen assembly with MHC class II protein complex | 0.389990
GO:0042102 | positive regulation of T cell proliferation | 0.389990
GO:0045087 | innate immune response | 0.302486
GO:0002455 | humoral immune response mediated by circulating immunoglobulin | 0.260326
GO:0032729 | positive regulation of interferon-gamma production | 0.260326
GO:0002729 | positive regulation of natural killer cell cytokine production | 0.260326
GO:0042270 | protection from natural killer cell mediated cytotoxicity | 0.260326
GO:0002506 | polysaccharide assembly with MHC class II protein complex | 0.260326
GO:0045953 | negative regulation of natural killer cell mediated cytotoxicity | 0.260326
GO:0050870 | positive regulation of T cell activation | 0.260326
GO:0002381 | immunoglobulin production involved in immunoglobulin mediated immune response | 0.260326
... | ... | ...
GO:2001190 | positive regulation of T cell activation via T cell receptor contact with antigen bound to MHC molecule on antigen presenting cell | 0.130663
GO:0071346 | cellular response to interferon-gamma | 0.130663
GO:0046979 | TAP2 binding | 0.130663
GO:0002666 | positive regulation of T cell tolerance induction | 0.130663
GO:2000774 | positive regulation of cellular senescence | 0.130663
GO:0042608 | T cell receptor binding | 0.130663
GO:0006968 | cellular defense response | 0.130663
GO:0046703 | natural killer cell lectin-like receptor binding | 0.130663
GO:0002767 | immune response-inhibiting cell surface receptor signaling pathway | 0.130663
GO:0042803 | protein homodimerization activity | 0.130663
GO:0051898 | negative regulation of protein kinase B signaling | 0.130663
GO:2001199 | negative regulation of dendritic cell differentiation | 0.130663
GO:0002717 | positive regulation of natural killer cell mediated immunity | 0.130663
GO:0042288 | MHC class I protein binding | 0.130663
GO:0007165 | signal transduction | 0.130663
GO:0002645 | positive regulation of tolerance induction | 0.130663
GO:0002715 | regulation of natural killer cell mediated immunity | 0.130663
GO:0070317 | negative regulation of G0 to G1 transition | 0.130663
GO:0070207 | protein homotrimerization | 0.130663
GO:0001915 | negative regulation of T cell mediated cytotoxicity | 0.130663
GO:0032736 | positive regulation of interleukin-13 production | 0.130663
GO:0050830 | defense response to Gram-positive bacterium | 0.130663
GO:2000353 | positive regulation of endothelial cell apoptotic process | 0.130663
GO:0045591 | positive regulation of regulatory T cell differentiation | 0.130663
GO:0042802 | identical protein binding | 0.130663
GO:0002451 | peripheral B cell tolerance induction | 0.130663
GO:0045580 | regulation of T cell differentiation | 0.130663
GO:0045954 | positive regulation of natural killer cell mediated cytotoxicity | 0.130663
GO:0032759 | positive regulation of TRAIL production | 0.130663
GO:0060907 | positive regulation of macrophage cytokine production | 0.130663

**Comment by jaredroach** [comment]
All four of these answers are correct, as a fairly quick researcher/immunologist guided Google search can validate. As an undergrad taking the MCAT, I would definitely pick (a). But I am not so sure Translator should be reporting back all of these as correct. I suppose the best case for (a) is made by inclusion of the word "essential". Maybe (b,c,d) functions are not essential. But ( c)  is absolutely essential IMHO in training B-lymphocytes (https://www.cell.com/trends/immunology/comments/S1471-4906(16)30151-X).
